# Generated by Django 5.1.3 on 2025-10-28 11:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_mentor', '0001_initial'),
        ('learning', '0002_careerpath_snsu_ccis_specific_and_more'),
        ('projects', '0002_remove_projecttask_created_by_project_course_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMentorSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('code_review', 'Code Review'), ('bug_detection', 'Bug Detection'), ('project_guidance', 'Project Guidance'), ('documentation_help', 'Documentation Help'), ('learning_recommendation', 'Learning Recommendation')], default='project_guidance', max_length=30, verbose_name='session type')),
                ('code_snippet', models.TextField(blank=True, verbose_name='code snippet')),
                ('user_question', models.TextField(verbose_name='user question')),
                ('ai_response', models.TextField(verbose_name='AI response')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20, verbose_name='status')),
                ('total_messages', models.IntegerField(default=0, verbose_name='total messages')),
                ('ai_model_used', models.CharField(default='gpt-4', max_length=50, verbose_name='AI model')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='tokens used')),
                ('cost_estimate', models.DecimalField(decimal_places=4, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='cost estimate')),
                ('temperature', models.DecimalField(decimal_places=2, default=0.7, help_text='Controls randomness in AI responses (0-2)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='temperature')),
                ('max_tokens', models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(4000)], verbose_name='max tokens per response')),
                ('user_rating', models.IntegerField(blank=True, help_text='User satisfaction rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='user rating')),
                ('feedback_text', models.TextField(blank=True, verbose_name='feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('last_activity', models.DateTimeField(auto_now_add=True, verbose_name='last activity')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('learning_resources', models.ManyToManyField(blank=True, related_name='recommended_in_sessions', to='learning.learningmodule', verbose_name='recommended learning resources')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_sessions', to='projects.project', verbose_name='project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_sessions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'AI chat session',
                'verbose_name_plural': 'AI chat sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.AlterField(
            model_name='aimessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_mentor.projectmentorsession', verbose_name='session'),
        ),
        migrations.AlterField(
            model_name='codeanalysis',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_analyses', to='ai_mentor.projectmentorsession', verbose_name='session'),
        ),
        migrations.AlterField(
            model_name='learningrecommendation',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='ai_mentor.projectmentorsession', verbose_name='session'),
        ),
        migrations.AlterField(
            model_name='projectguidance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_guidance', to='ai_mentor.projectmentorsession', verbose_name='session'),
        ),
        migrations.DeleteModel(
            name='AIChatSession',
        ),
    ]
