# Generated by Django 5.1.3 on 2025-10-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpath',
            name='snsu_ccis_specific',
            field=models.BooleanField(default=True, verbose_name='SNSU CCIS specific'),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='is_snsu_ccis_specific',
            field=models.BooleanField(default=False, help_text='Indicates if this module is specific to SNSU CCIS curriculum', verbose_name='SNSU CCIS specific'),
        ),
    ]
