# Generated by Django 5.1.3 on 2025-10-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_faculty_announcement',
            field=models.BooleanField(default=False, verbose_name='faculty announcement'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_official',
            field=models.BooleanField(default=False, verbose_name='official SNSU CCIS post'),
        ),
        migrations.AddField(
            model_name='post',
            name='program_relevance',
            field=models.CharField(choices=[('all', 'All Programs'), ('bsit', 'BS Information Technology'), ('bscs', 'BS Computer Science'), ('bsis', 'BS Information Systems')], default='all', max_length=20, verbose_name='program relevance'),
        ),
    ]
