# Generated by Django 5.1.3 on 2025-10-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttask',
            name='created_by',
        ),
        migrations.AddField(
            model_name='project',
            name='course_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='course code'),
        ),
        migrations.AddField(
            model_name='project',
            name='course_related',
            field=models.BooleanField(default=False, verbose_name='course related'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_snsu_ccis_project',
            field=models.BooleanField(default=True, verbose_name='SNSU CCIS project'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'Under Review'), ('completed', 'Completed')], default='todo', max_length=20, verbose_name='status'),
        ),
    ]
